trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Installing Node.js'

- task: Npm@1
  displayName: 'Installing NPM Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Building Angular Application'
  inputs:
    command: custom
    customCommand: run build -- --prod

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts'
  inputs:
    artifactName: angular
    pathtoPublish: 'artifacts'
