trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(Date:yyyy.MM.dd)$(Rev:.r)
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Installing Node.js'

- task: Npm@1
  displayName: 'Installing NPM Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Linting the Application'
  inputs:
    command: custom
    customCommand: run lint --  --format=stylish

- task: Npm@1
  displayName: 'Building the Application'
  inputs:
    command: custom
    customCommand: run build -- --prod

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts'
  inputs:
    artifactName: angular
    pathtoPublish: 'artifacts'

- task: GitHubRelease@0
  displayName: 'Creating GitHub Release'
  inputs:
    gitHubConnection: 'PatientViewer-NG-GitHub'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    tag: $(Build.BuildNumber)

