trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script:
    npm install -g @angular/cli
    npm install
    npm run test
    npm run prod
  displayName: 'Install Dependencies and Build'
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: artifacts
    pathtoPublish: 'artifacts'
  displayName: 'Publishing Artifacts'
